### ISSUE TITLE
KSP 1.12

### ISSUE THREAD

**Issue by victor-lopez17** [blowfishpro/SimpleAdjustableFairings-KWRocketry#8]
Having some issues using this with BDB’s fairings in 1.12… May need an update to work properly. 

![C64D8259-AF8B-4C7A-A6DF-DD28BDA65891](https://user-images.githubusercontent.com/101110510/158026939-d6fad5a2-9570-4df2-9384-68433ed39e1c.png)
![B2241328-C406-4EA5-BA32-A4932D1AF641](https://user-images.githubusercontent.com/101110510/158026942-02b44864-656a-4184-a38c-924c2081e1a9.png)

**Comment by blowfishpro** [comment]
Those look like the BDB parts, if there's a real issue please open it at the plugin repo not here, but I also haven't heard any other reports of there being an issue on 1.12
